export const reviewQuestions = [
  {
    questionId: 1,
    questionCategory: "Research Question",
    questionText: "Do you find the research question worthwhile?",
    minValue: 1,
    maxValue: 5,
    minLabel: "Not at all",
    maxLabel: "Completely",
  },
  {
    questionId: 2,
    questionCategory: "Design",
    questionText: "Do you find the way the study was conducted adequate?",
    minValue: 1,
    maxValue: 5,
    minLabel: "Not at all",
    maxLabel: "Completely",
  },
  {
    questionId: 3,
    questionCategory: "Findings",
    questionText: "Do you consider the findings sufficient to support the authors' claims?",
    minValue: 1,
    maxValue: 5,
    minLabel: "Not at all",
    maxLabel: "Completely",
  },
  {
    questionId: 4,
    questionCategory: "Interpretation",
    questionText: "Do you find the authors' explanation plausible?",
    minValue: 1,
    maxValue: 5,
    minLabel: "Not at all",
    maxLabel: "Completely",
  },
  {
    questionId: 5,
    questionCategory: "Significance",
    questionText: "How important do you think this study is for the society as a whole?",
    minValue: 1,
    maxValue: 5,
    minLabel: "Not at all",
    maxLabel: "Completely",
  },
]
